### ISSUE TITLE
upgrading from Typo3v10 to Typo3v11

### ISSUE THREAD

**Issue by ssavur-atl** [schams-net/nagios_extensionlist#13]
dear mr. @schams-net ,

I am upgrading from Typo3 version 10 to 11 and one of my obstacles is that the extension "nagios-extensionlist" is only compatible with Typo3v10. 

Are there alternatives (other extensions) that work with version 11 ? 
or are you in the process of making the extension compatible with version 11 ?

I would be very happy about your help.

With kind regards
Selahattin Savur

**Comment by schams-net** [comment]
A TYPO3 v11 compatible version is now available at the Git branch [typo3v11](https://github.com/schams-net/nagios_extensionlist/tree/typo3v11).

At the time of writing, the version hasn't been fully tested yet. Please test and provide feedback, so that I can publish a new official release of the extension.

**Comment by ssavur-atl** [comment]
dear @schams-net ,

I have successfully tested the branch "typo3v11" on Typo3v11 & PHP7.4 and everything works.
thank you very much for your support.

with kind regards 
Selahattin Savur

**Comment by schams-net** [comment]
Thanks for checking.
